name: MSBuild
on:
  push:
    branches:
      - master
  pull_request:

# Reference workflow: https://github.com/pbatard/libwdi/blob/master/.github/workflows/vs2022.yml
# But we specify library directories (WDK_DIR/LIBUSB0_DIR/LIBUSBK_DIR) via env variables directly.
# These are then used by libwdi-sys/build.rs to generate MSBuild command line with BuildMacros property.
env:
  WDK_URL: https://go.microsoft.com/fwlink/p/?LinkID=253170
  LIBUSB0_URL: https://sourceforge.net/projects/libusb-win32/files/libusb-win32-releases/1.2.7.3/libusb-win32-bin-1.2.7.3.zip/download
  LIBUSBK_URL: https://github.com/mcuee/libusbk/releases/download/V3.1.0.0/libusbK-3.1.0.0-bin.7z
  WDK_DIR: ../../../wdk/Windows Kits/8.0
  LIBUSB0_DIR: ../../../libusb0
  LIBUSBK_DIR: ../../../libusbk/bin

jobs:
  msbuild:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Download support files
        shell: cmd
        run: |
          curl -L ${{ env.WDK_URL }} -o wdk-redist.msi
          curl -L ${{ env.LIBUSB0_URL }} -o libusb0-redist.zip
          curl -L ${{ env.LIBUSBK_URL }} -o libusbk-redist.7z
          msiexec /a wdk-redist.msi /qn TARGETDIR=%CD%\wdk
          7z x libusb0-redist.zip
          7z x libusbk-redist.7z
          del *.zip
          del *.7z
          move libusb-win32* libusb0
          move libusbK* libusbk

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Cargo build
        # Use -vv to debug libwdi-sys/build.rs
        run: cargo build -vv --release
